name: anime-bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # cada 6 horas

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # ======================
      # 🟢 CLONAR REPO
      # ======================
      - name: Checkout
        uses: actions/checkout@v4

      # ======================
      # 🟢 NODE
      # ======================
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ======================
      # 🟢 INSTALAR DEPENDENCIAS
      # ======================
      - name: Install dependencies
        run: npm install

      # ======================
      # 🟢 EJECUTAR BOT
      # ======================
      - name: Run bot
        run: node bot.js
